# version: "3"

services:
  app:
    platform: linux/arm64
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - PORT=$PORT
    ports:
      - "443:${PORT}"
      - "3000:3000"
    environment:
      PORT: 3000
      # VITE_DOMAIN: "beatbump.ml"
      # VITE_SITE_URL: "https://beatbump.ml"
      VITE_DOMAIN: "beatbump.yunhocho.com"
      VITE_SITE_URL: "https://beatbump.yunhocho.com"
  proxy:
    build:
      context: ./packages/proxy-server/deno
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
